In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

y_true = [0, 1, 1, 0, 1]
y_pred = [0, 0, 1, 0, 1]

cm = confusion_matrix(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
mae = mean_absolute_error(y_true, y_pred)
#rmse = mean_squared_error(y_true, y_pred, squared=False)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
print("Confusion Matrix:\n", cm)
print("Precision:", prec)
print("Recall:", rec)
print("F1 Score:", f1)
print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)

Confusion Matrix:
 [[2 0]
 [1 2]]
Precision: 1.0
Recall: 0.6666666666666666
F1 Score: 0.8
Mean Absolute Error: 0.2
Root Mean Squared Error: 0.4472135954999579


Task 1

Fraud Detection

Performance metrics

In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

y_true = [1]*85 + [0]*900 + [1]*5 + [0]*15
y_pred = [1]*85 + [0]*900 + [0]*5 + [1]*15

cm = confusion_matrix(y_true, y_pred)
acc = accuracy_score(y_true,y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true,y_pred)

print("Confusion matrix: ")
print(cm)

print("Accuracy: ",acc)
print("Precision_score: ",prec)
print("Recall: ",rec)
print("F1 score: ",f1)

Confusion matrix: 
[[900  15]
 [  5  85]]
Accuracy:  0.9800995024875622
Precision_score:  0.85
Recall:  0.9444444444444444
F1 score:  0.8947368421052632


Task 2

Another metrics example

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

y_true =  [1]*80 + [0]*90 + [1]*20 + [0]*10
y_pred = [1]*80 + [0]*90 + [0]*20 + [1]*10

cm = confusion_matrix(y_true,y_pred)
acc = accuracy_score(y_true,y_pred)
prec = precision_score(y_true,y_pred)
rec = recall_score(y_true,y_pred)
f1 = f1_score(y_true,y_pred)

print("Confusion matrix:")
print(cm)

print("Accuracy: ",acc)
print("Precision: ",prec)
print("Recall: ",rec)
print("F1 Score: ",f1)

Confusion matrix:
[[90 10]
 [20 80]]
Accuracy:  0.85
Precision:  0.8888888888888888
Recall:  0.8
F1 Score:  0.8421052631578947


Task 3

In [5]:
from sklearn.metrics import mean_squared_error
import math

y_true = [10,20,30,40]

pred_a  = [12,19,33,41]

pred_b = [11,20,29,40]

rmse_a = math.sqrt(mean_squared_error(y_true,pred_a))
rmse_b = math.sqrt(mean_squared_error(y_true,pred_b)) 

print("RMSE Model A: ",rmse_a)
print("RMSE Model B: ",rmse_b)

if rmse_a < rmse_b:
    print("Model A is better")
else:
    print("Model B is better")

RMSE Model A:  1.9364916731037085
RMSE Model B:  0.7071067811865476
Model B is better
